#!/bin/bash
lock() {
   # i3lock
    BLANK='#00000000' 
    CLEAR='#ffffff22' 
    DEFAULT='#ff00ffcc' 
    TEXT='#ee00eeee' 
    WRONG='#880000bb' 
    VERIFYING='#bb00bbbb' 
     
    i3lock \
    --insidever-color=$CLEAR     \
    --ringver-color=$VERIFYING   \
    \
    --insidewrong-color=$CLEAR   \
    --ringwrong-color=$WRONG     \
    \
    --inside-color=$BLANK        \
    --ring-color=$DEFAULT        \
    --line-color=$BLANK          \
    --separator-color=$DEFAULT   \
    \
    --verif-color=$TEXT          \
    --wrong-color=$TEXT          \
    --time-color=$TEXT           \
    --date-color=$TEXT           \
    --layout-color=$TEXT         \
    --keyhl-color=$WRONG         \
    --bshl-color=$WRONG          \
    \
    --screen 1                   \
    --blur 6                     \
    --clock                      \
    --indicator                  \
    --time-str="%H:%M:%S"        \
    --date-str="%A, %Y-%m-%d"    \
    --keylayout 1                \
    -n

}

case "$1" in
    lock)
	pkill -u "$USER" -USR1 dunst
	sleep 0.1
        lock
	pkill -u "$USER" -USR2 dunst
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
